name: complete_flutter_project_starter
description: A Flutter Project Starter with very useful libraries and boilerplate code to help you setup your Flutter projects in minutes.

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^5.0.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  lint: ^2.0.1
  mockito: ^5.1.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
